name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - name: Fmt
      run: cargo fmt -- --check --config imports_granularity=Crate,group_imports=StdExternalCrate
    - name: Clippy
      run: cargo clippy
